### ISSUE TITLE
`Ctrl+p` autocomplete has become slower after updating from 72d5dd2 to 7372295

### ISSUE THREAD

**Issue by bogdanvlviv** [tpope/vim-bundler#50]
Hello, I've updated this plugin from 72d5dd2 to 7372295. After this vim autocomplete by `Ctrl+p` has become slower since it scans all gems that in my Gemfile.lock I guess.

![screenshot from 2018-07-01 00-42-02](https://user-images.githubusercontent.com/6443532/42129305-1065ee24-7cca-11e8-92a7-b3b1fa25f88d.png)

Execution of `Ctrl+p` takes me about 30seconds on the project https://github.com/rails/rails

**Comment by tpope** [comment]
It scans all files that are loaded by `require` the current file. Indeed it can get slow if you're requiring something with a large number of dependencies. This has been the behavior since forever so I'm guessing it was happening before you upgraded (you might not have noticed because you were editing files with fewer `require`s).

I recommend `:set complete-=i`, to turn off completion of completed files.

**Comment by bogdanvlviv** [comment]
Thanks for the explanation.
